# --- Seguridad JWT ---
#mp.jwt.verify.publickey.location=publicKey.pem
#mp.jwt.verify.issuer=https://erp.svsoluciones.com/issuer
# --- Liquibase ---
quarkus.liquibase.migrate-at-start=true
# La ruta donde Liquibase buscará el archivo maestro
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml
# --- 1. Apagar Dev Services (Usar mi propio Docker local) ---
quarkus.datasource.devservices.enabled=false

# --- 2. Conexión a la Base de Datos ---
quarkus.datasource.db-kind=postgresql
# OJO: Aquí ponemos localhost porque Quarkus corre en tu máquina, no dentro de Docker
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/svsoluciones_erp
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# --- 4. Hibernate (Apagar su generación porque Liquibase manda) ---
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.packages=com.svsoluciones.erp.infrastructure.output.persistence.entity